### ISSUE TITLE
method signature for `build_state_predictor` is hard to match

### ISSUE THREAD

**Issue by blakejohnson** [BBN-Q/QuantumTomography.jl#3]
The method signature is `build_state_predictor(obs::Vector{Matrix})`. The problem is that without specifying a type for `Matrix`, the only thing that will match this is another `Matrix` with unspecified type. Solution is either to explicitly allow allow types, i.e. write this as:
```julia
build_state_predictor{T}(obs::Vector{Matrix})
```
Or just drop the `Matrix` and let any `Vector` suffice.

**Comment by marcusps** [comment]
I assumed that the current signature was equivalent to what you suggested.  I lean towards using the type parameter. Thoughts?

**Comment by blakejohnson** [comment]
I think we should just add the type parameter. Incidentally, I noticed you have sprinkled `Matrix` types in front of various `Vector`s throughout the test code. Note that something like `Matrix[rand(2,2)]` produces a vector of type `Array{Array{T,2},1}` (note the `T` still hanging around there), whereas if you drop the `Matrix` you get the tighter type `Array{Array{Float64,2},1}`. I guess the lesson is that when you write `Vector` or `Matrix`, there is an implied type parameter that you ought to either specify, or allow it to be generic and capture it in the method signature.
