### ISSUE TITLE
Hermitian condition too strict?

### ISSUE THREAD

**Issue by dieris** [BBN-Q/QuantumTomography.jl#9]
Because of rounding error (~1e-16), [this](https://github.com/BBN-Q/QuantumTomography.jl/blob/27129ff667570b0441ac757208d93673af7c1320/src/state-tomo.jl#L25) condition is not always satisfied exactly (the difference may be ~1e-16). Should we round `obs` to some precision?

**Comment by marcusps** [comment]
One way to fix this is to make your observables hermitian
```julia
function hermitian_projection(m)
  return (m+m')/2
end
```
We can also increase the tolerance of the `ishermitian` test and then do that projection afterwards, for sanity.

**Comment by matthewware** [comment]
I believe we are now doing this in Qlab.jl before passing in the data.  I think that's the best way to handle this for now.  If there are no objections, I'll close this issue.
